path: /content/drive/MyDrive/YOLO_project/data
train: images/train
val: images/val

nc: 7
names:
  0: Calculator
  1: Lamp
  2: Keyboard
  3: Laptop
  4: Monitor
  5: Mouse
  6: Mug

hsv_h: 0.015
hsv_s: 0.4     
hsv_v: 0.2     
degrees: 10.0
translate: 0.1
scale: 0.3     
shear: 2.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.1      
copy_paste: 0.0